{{
    config(
        materialized='table'
    )
}}

WITH events AS (
    SELECT * FROM {{ ref('src_events') }}
)

SELECT  events.USER_GUID
        ,events.SESSION_GUID
        ,MIN(events.CREATED_AT_UTC) AS SESSION_STARTED_AT_UTC
        ,MAX(events.CREATED_AT_UTC) AS SESSION_ENDED_AT_UTC
        ,TIMESTAMPDIFF('second',SESSION_STARTED_AT_UTC,SESSION_ENDED_AT_UTC) AS SESSION_DURATION_S
        ,ROUND(SESSION_DURATION_S/60.0,2) AS SESSION_DURATION_M
        ,ROUND(SESSION_DURATION_M/60.0,2) AS SESSION_DURATION_H
        ,SUM(CASE WHEN events.EVENT_TYPE = 'page_view' THEN 1 ELSE 0 END) AS SESSION_PAGE_VIEWS
        ,SUM(CASE WHEN events.EVENT_TYPE = 'add_to_cart' THEN 1 ELSE 0 END) AS SESSION_ADD_TO_CARTS
        ,SUM(CASE WHEN events.EVENT_TYPE = 'checkout' THEN 1 ELSE 0 END) AS SESSION_CHECKOUTS
        ,SUM(CASE WHEN events.EVENT_TYPE = 'package_shipped' THEN 1 ELSE 0 END) AS SESSION_PACKAGES_SHIPPED
        ,COUNT(DISTINCT events.PRODUCT_GUID) AS SESSION_DISTINCT_PRODUCTS
        ,COUNT(DISTINCT events.ORDER_GUID) AS SESSION_DISTINCT_ORDERS
FROM events
GROUP BY    events.USER_GUID
            ,events.SESSION_GUID